### ISSUE TITLE
Show a photo of a judo technique

### ISSUE THREAD

**Issue by deriancastro** [deriancastro/capstone-project#2]
## Value statement(User story)
**As a** athlete
**I want to** see a photo of a specific judo technique
**I order to** know the details of the execution of a judo technique

## Description (Text, Scribble, Wireframe, Design)
![431489D0-7326-4678-BCCA-5B47BDE02972](https://user-images.githubusercontent.com/82398283/120602979-d0d2cf80-c44b-11eb-890d-04421fd9f47e.png)

## Acceptance criteria
- [ ]A title centered and fixed at the top with the name of the technique
- [ ]A centered photo of a judo technique

## Complexity
low

## Tasks
- [ ] Create feature branch
- [ ] Update card component
- [ ] Update component test
