### ISSUE TITLE
Goals list

### ISSUE THREAD

**Issue by deriancastro** [deriancastro/capstone-project#3]
## Value statement(User story)
**As a** athlete
**I want to** have a list of my training objectives
**I order to** track my objectives with an todo list

## Description (Text, Scribble, Wireframe, Design)
![1F0446AC-2975-4DF3-BE6C-E3D3AF954BF4](https://user-images.githubusercontent.com/82398283/120609082-29a56680-c452-11eb-9500-bedb7cb45b7b.png)

## Acceptance criteria
- [ ]A title centered and fixed at the top: "Goals"
- [ ]A list of 5 objectives and their respective checkboxes
- [ ]Scrolling list
- [ ]Navegation links

## Complexity
medium

## Tasks
- [ ] Create feature branch
- [ ] Build goal component(storybook)
- [ ] Write tests for goal component
- [ ] Add goals to App
