### ISSUE TITLE
Home page and navigation 

### ISSUE THREAD

**Issue by deriancastro** [deriancastro/capstone-project#4]
## Value statement(User story)
**As a** athlete
**I want to** have a profile
So **I can see information** about myself 

## Description (Text, Scribble, Wireframe, Design)
![76B4E0B5-1050-49D9-BF2A-5A3796C95084](https://user-images.githubusercontent.com/82398283/120698719-b6324200-c4af-11eb-97f2-1532131d06fb.png)

## Acceptance criteria
- [ ]A title centered and fixed at the top with the name of the team
- [ ]A profile photo
- [ ]A "about me" section: user photo, user name and text field
- [ ]A navigation between home, goals and tutorial pages
- [ ]The URL changes

## Complexity
Medium

## Tasks
- [ ] Create feature branch
- [ ] Build navigation component(storybook)
- [ ] Write test for navigation
- [ ] Add navigation to home page
- [ ] Build home page component
- [ ] Write tests for home page component
- [ ] Add home page to App
