### ISSUE TITLE
Save goals, profile and judo techniques at localstorage

### ISSUE THREAD

**Issue by deriancastro** [deriancastro/capstone-project#5]
## Value statement(User story)
**As a** athlete
**I want to** save my profile info and goals
So **I can always have my information**  at all times

## Description (Text, Scribble, Wireframe, Design)
![62082BFC-9DE0-47C3-91A1-5030F02BD73B](https://user-images.githubusercontent.com/82398283/120701202-d7486200-c4b2-11eb-9e7e-b6e7cd6f09bd.png)

## Acceptance criteria
- [ ]information such as goals, profile and judo techniques are always accessible, even if the browser is refreshed

## Complexity
Medium

## Tasks
- [ ] Create feature branch
- [ ] Use local storage hook
