### ISSUE TITLE
Add log in and save all info at MongoDB

### ISSUE THREAD

**Issue by deriancastro** [deriancastro/capstone-project#6]
## Value statement(User story)
**As a** athlete
I **can login** 
So **only I can access my information** and no one else

## Description (Text, Scribble, Wireframe, Design)
![FD9AF76B-8FD6-4510-B465-F2B7F6268890](https://user-images.githubusercontent.com/82398283/120706835-dff06680-c4b9-11eb-8c74-92760c9b64f2.png)

## Acceptance criteria
- [ ] A title centered and fixed at the top with the name of the App
- [ ] The user must log in to access the home page
- [ ] The form consists of validations such as: no blank spaces or invalid characters
- [ ] Each field is mandatory
- [ ] The login button is activated if the form is filled in correctly
- [ ] MongoDB must be run locally
- [ ] Information such as goals, profile and judo techniques are saved at MongoDB

## Complexity
High  

## Tasks
- [ ] Create feature branch
- [ ] Build form component(storybook)
- [ ] Write test for form component
- [ ] Build login page component
- [ ] Add form to login page
- [ ] Write test for login page
- [ ] Write Backend logic
- [ ] Use MongoDB
